config/routes.rb
Rails.application.routes.draw do
  get 'repositories/list'
  resources :repositories, only: [:index, :show] do
    post "review_comment", on: :collection
  end

  get 'home/index'
  match "/auth/github/callback", to: 'sessions#create', via: :all
  match "/signout", to: 'sessions#destroy', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

	def self.create_or_update_with_omniauth(auth)
		user = self.find_by_uid(auth["uid"])
		user = self.create(uid: auth["uid"], access_token: auth["credentials"]["token"], nick_name:  auth["info"]["nickname"], name:  auth["info"]["name"]) unless user
		user
  end

  def fetch_review_comment(data)
    from = data[:from].to_i
    to = data[:to].to_i
    review_comments = []
    if to >= from
      from.upto(to) do |pull|
        url = "#{Settings.github_url}repos/#{data['owner']}/#{data["repo"]}/pulls/#{pull}?access_token=#{self.access_token}"
        response = Typhoeus.get(url)
        break if response.response_code != 200
        pull_request_obj = parse_json_data response
        if pull_request_obj["review_comments"] > 0
          url = "#{pull_request_obj["review_comments_url"]}?access_token=#{self.access_token}"
          response = Typhoeus.get(url)
          review_objs = parse_json_data response
          review_objs.each do |review_obj|
            review_comments.push([pull, pull_request_obj["title"], pull_request_obj["body"], review_obj["body"],
                                  pull_request_obj["user"]["login"], review_obj["user"]["login"], review_obj["path"]])
          end
        else
          review_comments.push([pull, pull_request_obj["title"], pull_request_obj["body"], "",
                                pull_request_obj["user"]["login"], "", ""])
        end
      end
    end
    review_comments
  end

  def parse_json_data response
    begin
      ActiveSupport::JSON.decode(response.response_body)
    rescue ActiveSupport::JSON.parse_error
      Rails.logger.warn("Attempted to decode invalid JSON")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

  def index
    url = "#{Settings.repos}#{current_user.access_token}"
    response = Typhoeus.get(url)
    begin
      @respositories = ActiveSupport::JSON.decode(response.response_body)
    rescue ActiveSupport::JSON.parse_error
      Rails.logger.warn("Attempted to decode invalid JSON: #{some_string}")
    end
  end

  def show
  end

  def review_comment
    @review_comments = current_user.fetch_review_comment(params)
    respond_to do |format|
      format.html
      format.xlsx {render xlsx: 'review_comment',filename: "review_comment.xlsx"}
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		auth = request.env["omniauth.auth"]
		user = User.create_or_update_with_omniauth(auth)
		session[:user_id] = user.id
		# redirect_to repositories_path, :notice => "Signed in!"
    redirect_to root_path
	end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<div class="text-center">
  <div>
    <%= image_tag("emids_logo") %>
  </div>
  <div class="info">
    <% if current_user %>
        <h1>Welcome <%= current_user.name %></h1>
    <% else %>
        <%= link_to "Sign in with Github", "/auth/github", class: "btn btn-success btn-lg btn-block" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmidsGithub</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<!-- <div id="spinner" class="hidden">
  <div class="loader"></div>
</div> -->
<header class="navbar navbar-static-top" id="top">
  <div class="container">
    <div class="navbar-header float-left">
      <a class="navbar-brand" href="/">EmidsGithub</a>
    </div>
    <nav class="navbar-collapse" id="bs-navbar">
      <ul class="nav navbar-nav float-left">
        <% if current_user %>
        <li><%= link_to "Repository", repositories_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right float-right">

          <% if current_user %>
              <li><span class="welcome">Logeed in as! <%= current_user.nick_name %></span></li>
            <li><%= link_to "Sign Out", signout_path %></li>
          <% else %>
              <li><%= link_to "Sign in with Github", "/auth/github" %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/repositories/index.html.erb
<h1>Repositories#list</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Full Name</th>
    <th>Owner</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>

  <% @respositories.each do |repository| %>
      <tr>
        <td><%= repository["id"] %></td>
        <td><%= repository["name"] %></td>
        <td><%= repository["full_name"] %></td>
        <td><%= repository["owner"]["login"] %></td>
        <td><%= link_to 'Pull Request',repository_path(id: repository["name"], owner: repository["owner"]["login"]),class: 'btn btn-success' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/repositories/review_comment.html.erb
<h1>Review And Comment#list</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>PullRequest</th>
    <th>Title</th>
    <th>Description</th>
    <th>Comment</th>
    <th>Developer</th>
    <th>Reviewer</th>
    <th>FileName</th>
  </tr>
  </thead>
  <tbody>

  <% @review_comments.each do |reviews| %>
      <tr>
        <% reviews.each do |review| %>
            <td><%= review %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/repositories/show.html.erb
<h1><%= params["id"] %> Repository</h1>
<hr/>
<!--<div class="info"></div>-->
<h2>Fetch Pull Request Info</h2>
<hr/>
<%= form_tag(review_comment_repositories_path(format: "xlsx"), method: "post", class: "form-inline") do %>
    <div class="form-group">
      <label for="from-no">From</label>
      <%= text_field_tag(:from, "", class: "form-control", placeholder: "10") %>
    </div>
    <div class="form-group">
      <label for="to-no">To</label>
      <%= text_field_tag(:to, "", class: "form-control", placeholder: "30") %>
    </div>
    <%= hidden_field_tag(:repo, params["id"]) %>
    <%= hidden_field_tag(:owner, params["owner"]) %>
    <button type="submit" class="btn btn-success">Review Comment</button>
<% end %>